apiVersion: v1
kind: Service
metadata:
  name: {{ include "todoapp.fullname" . }}
  labels:
    {{- include "todoapp.labels" . | nindent 4 }}
    release: prometheus
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "todoapp.selectorLabels" . | nindent 4 }}